### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by Christina0717** [DeepLearnXMU/mc_tit#5]
Thanks for your great work. While runnning the 2nd stage, bash fairseq-codebook-pretrain.sh, the followng issue came out. It would be wonderful if you can help me figure out the possible reason of this issue:

Traceback (most recent call last):
  File "/data/guowenyu/anaconda3/envs/tit/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/data/guowenyu/mc_tit/fairseq_cli/train.py", line 558, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/data/guowenyu/mc_tit/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/data/guowenyu/mc_tit/fairseq_cli/train.py", line 191, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/data/guowenyu/anaconda3/envs/tit/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/data/guowenyu/mc_tit/fairseq_cli/train.py", line 317, in train
    log_output = trainer.train_step(samples)
  File "/data/guowenyu/anaconda3/envs/tit/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/data/guowenyu/mc_tit/fairseq/trainer.py", line 857, in train_step
    raise e
  File "/data/guowenyu/mc_tit/fairseq/trainer.py", line 831, in train_step
    **extra_kwargs,
  File "/data/guowenyu/mc_tit/fairseq/tasks/fairseq_task.py", line 521, in train_step
    optimizer.backward(loss)
  File "/data/guowenyu/mc_tit/fairseq/optim/fairseq_optimizer.py", line 95, in backward
    loss.backward()
  File "/data/guowenyu/anaconda3/envs/tit/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/data/guowenyu/anaconda3/envs/tit/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: device-side assert triggered

**Comment by Nonoor** [comment]
Sorry for the late reply. This error may be caused by an index out of bounds. First, please make sure that the vocabulary used in the second stage is consistent with the first stage. Additionally, you can set os.environ['CUDA_LAUNCH_BLOCKING'] = '1' or run the program on the CPU to ensure the actual error position.

**Comment by Christina0717** [comment]
Thank you for your considerate response. It has assisted me in resolving the issue.
